import React, { Component } from 'react';
//import ReactDOM from 'react-dom'
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import { Carousel } from 'react-responsive-carousel';

class Newcarousel extends Component {
  render() {
    return (
      <Carousel
        infiniteLoop
        autoPlay
        interval={3000}
        transitionTime={350}
        showThumbs={false}
        showStatus={false}
      >
        <div>
          <img
            src="https://lh3.googleusercontent.com/X7OOyK-wWk6UbObGEUYg_W0Pek9DNIyWY66VebhqmJKiVTQ2oVHFKFeBZDKRNW6ZxDLI25XKaG4d6Rg2c8vLwd7CM-Yq3G20nbnewxf7z9YrzyGU2qcqFiXJmZK5MPYZeXgfx9NEkzg=w2400"
            alt="1"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/-n7ONRZTp9xVBCc1y7M2OxCYrVKTI8BXttW1TLjHqAmCC0DYZNdK3RZFHIq_KIcmchwdZitBNeg06oSnphKmFBFx8z9zDjFmHLBrpXspGnQGfxPs-rmZRztIz-uKzBROsqZgPTojq2M=w2400"
            alt="2"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/kWrCNZdDI-BomXgykvZHH598pl8FDY5zA7AOCNRox4tvI8e2v65IbDCAKGLjFHhKn5FlO9Qcm3LtSYM_5QfJfgU0qMw7YG2J-xhG64ULbAOsPXQFUlFqsS08t362yB_s8G2_SpkELMg=w2400"
            alt="3"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/aio0RHspZt9SR7xAr24tl476T434AQAfU2rGK441cCDwWVpOSaXHuGwK88kmh33ZozryxOjvoFnc-mdA_808L8fr6QVCvD8Nv5GGM0RJdD8nX5gdgsqLw9GXLFboqjxfMsm6XaGIgag=w2400"
            alt="4"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/SAqXtSTD4lQOWDOcTPvazvlG-LOmhjGNdTLJWX8vZwIU-Sp_ZnmQ-cDPtgdH5ACMenm4dg8wzCv2ftJ-abgv9LaOzEGsKejyymctnkYEkB5os9QUbPFJvO8sdW6cmfB8uHdGWyKOpE4=w2400"
            alt="5"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/8d8QnbQ9yIRK0CSv9mjMuoLc7bV-M55GH-yKtiyOKDAsnPFszjJ2pIpJbPKutu2fACreWzthf9cdzzTiR9ADBi2UHjhGU7p6wNPmoQEPIOwIuNNYyjSRjdfuVQcjXEo6nEjn5A4Gx38=w2400"
            alt="6"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/QknjKdPeL18TcrbChM2m13ehdagkjxLg8YmFs5PPommvRKbct6j2bF47RCubt_TUpQkHDsIPp87o4i6BVXL-4PtOUKs5Jc8yE5QgZNUm79ntR03PyFvz0MqikmPdKRzBh-r285rNxWA=w2400"
            alt="7"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/sc7IP_qQFMhia7pPdRMcTiC0Vyh9eWO8DeOaJ4YLM3BiljtV_5Ap1aLhU7Ge9zvzUFRuL76owI4G6OcXuLFQbzHuvRX3PKBE1A8XB1aw5Mbtk6iM0cIZTNSuxGo3FGP4D6D8WA_JAYo=w2400"
            alt="8"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/_jQJd_aO6WIgvBjGR8IU75wg9ntSVyi15KHz8RvADYkotG-dxad87PYH09uooKVFWiHJxMxDAlC6zEmM1YEk5GU9smU3sOTvadqachRinmhvEtWpBUUACnR-cxao9GGAQyAX7QTzhMA=w2400"
            alt="9"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/HqL5SVnDw6qf6HlFbV731-W7rLVCA5fuXTiwWtRELJyogt6_--HV0J30jPIQQWxZeYr5Yt5uhCIy6jN1uxyFjn5kWC-MCfYDDsbaRwv1yVScKhE8nZbu0F790H79z8u_6mw3ndFFCmU=w2400"
            alt="10"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/U2KiaU4m6SxcgMjEDNCPN0MNy9f68zeOLESPl1Gbm41nzT2UoEQEUc7mr9uokr2Yds4RpO-z2fDCNhVuIvndPHc6RklVnDgs5zexIivdAOvvpcxJ-qFtxLz175EafFvm7nqr8e0gHU4=w2400"
            alt="11"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/t-K2KGAF8J8CMSv-vEPAAwaZl8LcPc1-PRGjOFXnAJ80TWzhkHyTxEFmbHigzCFGo-4igRkivbO01kYLC_xGCMUizkZXOSN4QA9bb_d2jfTt6LuuaNpL-WhB90eQKJacNv2P7c1YIU4=w2400"
            alt="12"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/d0xHRVPeVQeCruyY-Zkrg06IfMqt5khxV70H-Lxsc6dOB1JrXsd7um0UCNn8Xh_K1drPaW3_cChse0MsUkIi2jFzjLRyZgJ9wqYPmwXO0jjcx8zkyP9kdpPsvDgxSFMycrYamEf29HY=w2400"
            alt="13"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/JKe0HWU-kwDJYIPssRdmCFNyS2SuOmgmiIvENVD5QY45PL0qkmjfzhguDf-eekOxEPEOnJffKgCwN9NOorv9vSWDk3nV_ljP16lCWfBeBtLm2A46yzdMtw_qCVisj8yPM1felvCcW3w=w2400"
            alt="14"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/kmFJH0OgzxUsN9WA3Mxrci9ZO9vk2AzkkLb-kaHQlVkZs1ejPNvodhVgFk2MkZUH7Ve1F7KkhRSqniTeSj4tJQyjNfCc-ueTPQ5isBpncf_Nd3xos4giO_2IcPErtuGQUWyTs5jy8kk=w2400"
            alt="15"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/NwAvfQi3k2eJF20U7iO-d2Ht4ySvAenfQpEu-yJ_-ikc_Y5KdN0l7_uQH--JPPNKJJxwzvTwauplhyCMHr--3Hxq718r3Q7rrMRp4MikHtkEPwmcoNNPT3kpfliOEeO2mbcr5OR1wbY=w2400"
            alt="16"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/N5VHfCsuLYQ6XJJMjQJffFTZYx6qTWtnsfNAW4EL0Ncq7oZ2hSlIisG79GSoph2_rkKZbHmzIcYGRke68KceS1nF-0L9CmfZ_L6sJjz9jkGHTJB9CEMRxH-1Q40uajIoyEbzu9RedEg=w2400"
            alt="17"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/gi_QFMwaMOVkqt2x3c7AIad0iWknvw_sqAk_yIHfcFFvwYdDxJ6vwkhExVDFZ_t_znNUrMy4I53rM6D3R-plhtj_gnrNo4-_hIFu9V9IgYaq8EIQE1vpwFQ5ockgIwZZ8G1mxStFDzw=w2400"
            alt="18"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/XSB4D9SC-EFvyxgPSsHCNMqa4WnvOwQWTMbqi65KQ2ZoXUNRNJFbIIkRNJJyJSZBS4FKFLj3npDAnCbA98Ws74ng1vboCV3DtOIZ_qqSz1pWj39itx-RikfCpDno1pJOYk3rZiI_z60=w2400"
            alt="19"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/8jOPBSKnwq9zqUeCB-2KQcWrqHqN4-WfR3npK6LTGwS7JNk50bB5XVSphR-91FX0uyS72Re534sVU_0ZQ9F_ytSLsfco5z-A8qkMaSpTOBgIyymsikXf87MY2D9p9EBVqyhAbDD6wdw=w2400"
            alt="20"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/WD3l4tRco27p5zdrkh-M-WoQFuMRiDIkktUZbbqGe1Fuyi9AXklX96uZRvmzqbjp_LltiQp0j5C2htA0ykfhnJ1K8smneQw7DBRxFckSElZGfxXCBmVWEtaaL7PzEvtxGWnRebS-Iq8=w2400"
            alt="21"
          />
        </div>
        <div>
          <img
            src="https://lh3.googleusercontent.com/yGcQm07zAQXU8u1HXzeI1RNT7Am-xO8Ix3iKEIo9587kcGNdr55-BY-skga479lxqZnH3t7VQrBFjrVY5hCe6VlgsrS46yLME6e_qDTIfcj_OG1r379AQVUWpmsjKLz3XNF_SKwXn80=w2400"
            alt="22"
          />
        </div>
      </Carousel>
    );
  }
}

export default Newcarousel;

// Don't forget to include the css in your page

// <link rel="stylesheet" href="node_modules/react-responsive-carousel/lib/styles/carousel.min.css"/>
